pubs.html: pubs.md
	pandoc -s -t html5 --css ../css/mvp.css -o pubs.html pubs.md

# To use this, make edits to pubs.md, then type:
#
# $ make
#
# at the command line in order to create (or update) the html file. 
